# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	loom_version=1.16-SNAPSHOT
	minecraft_version=26.1.2
	loader_version=0.19.2

# Mod Properties
	mod_version = 1.0.0-TEST-1
	maven_group = io.github.skippyall
	archives_base_name = Minions

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_api_version=0.147.0+26.1.2

	polymer_version=0.16.3+26.1.2
	sgui_version=2.0.0+26.1
	server_translations_version=3.0.3+26.1

	night_config_version=3.8.3

	universal_graves_version=3.11.0+26.1.2
